### interchange first and last elements in a list

Input : [12, 35, 9, 56, 24]
    
Output : [24, 35, 9, 56, 12]
    
    
    
    

Input : [1, 2, 3]
    
Output : [3, 2, 1]

In [1]:
def swapitem(newlist):
    n = len(newlist)
    
    temp = newlist[0]
    newlist[0] = newlist[n-1]
    newlist[n-1] = temp
    
    return newlist

newlist = [12, 35, 9, 56, 24]


print(swapitem(newlist))

[24, 35, 9, 56, 12]


### to Swap Two Elements in a List

Input : List = [23, 65, 19, 90], pos1 = 1, pos2 = 3
Output : [19, 65, 23, 90]

Input : List = [1, 2, 3, 4, 5], pos1 = 2, pos2 = 5
Output : [1, 5, 3, 4, 2]



In [2]:
def swap_position (arr, pos1, pos2):
    arr[pos1], arr[pos2] = arr[pos2], arr[pos1]
    return arr


arr = [23, 65, 19, 90]
pos1= int(input("enter the position of first element: "))
pos2= int(input("enter the position of second element: "))

   
print(swap_position(arr, pos1-1, pos2-1)) # -1 because array starts from 0



enter the position of first element: 4
enter the position of second element: 2
[23, 90, 19, 65]


### Length of a List in Python

In [3]:
list1= list((10 , 20 , 345))
n= len(list1)
print ("length of the list is",n)

length of the list is 3


### Check if element exists in list in Python


In [4]:
test_list = [1, 6, 3, 5, 3, 4]

i=int(input("ENTER THE NUMBER TO CHECK: "))

if i in test_list:
    print("exist")
else:
    print("not exist")

ENTER THE NUMBER TO CHECK: 12
not exist


### Different ways to clear a list in Python


In [5]:
list1 = [6, 0, 4, 1]
print("before clearing ", list1)

list1.clear()
print("after clearing list", list1)

before clearing  [6, 0, 4, 1]
after clearing list []


### Reversing a List in Python


Input: list = [4, 5, 6, 7, 8, 9]
    
    
Output : [9, 8, 7, 6, 5, 4] 

In [6]:
def reverce(lst):
    new_list = lst[::-1]
    return new_list

lst = list((10, 415,42,58,46,12,11))

print(reverce(lst))

[11, 12, 46, 58, 42, 415, 10]


In [7]:
lst

[10, 415, 42, 58, 46, 12, 11]

In [8]:
lst = [11, 12, 46, 58, 42, 415, 10]
print("brfore using reverse keyword:", lst)

lst.reverse()

print("after using reverse keyword", lst)

brfore using reverse keyword: [11, 12, 46, 58, 42, 415, 10]
after using reverse keyword [10, 415, 42, 58, 46, 12, 11]


In [9]:
#using for loop 

lst = [11, 12, 46, 58, 42, 415, 10]

reverced_list = []

for i in lst:
    reverced_list.insert(0,i)
print(reverced_list)

[10, 415, 42, 58, 46, 12, 11]


### to find sum of elements in list

Input: [12, 15, 3, 10]
Output: 40

    
    
Input: [17, 5, 3, 5]
Output: 30

In [10]:
def sum_(lst):
    total = 0
    for i in range(len(lst)):
        total = total + lst[i]
        
        
    return total


#driven code
lst = [12, 35, 9, 56, 24]
print("sum of list is", sum_(lst))

sum of list is 136


In [11]:
total = 0 

lst = [12, 35, 9, 56, 24]


for i in range (0, len(lst)):
    total = total + lst[i]
    
    
print("total of the list is ", total)

total of the list is  136


In [12]:
total = 0
i = 0

lst = [12, 35, 9, 56, 24]


while(i < len(lst)):
    total = total + lst[i]
    i+=2
    
print("sum of the list is :", total)

sum of the list is : 45


### Python program to count positive and negative numbers in a list

In [13]:
list1 = [10, -21, 4, -45, 66, -93, 1]
pos_count = 0
neg_count = 0

for i in list1:
    
    
    if i >= 0:
        pos_count += 1
    else:
        neg_count += 1

        
print("positive numbers in the list are: ", pos_count)
print("negative numbers in the list are : ", neg_count)


positive numbers in the list are:  4
negative numbers in the list are :  3


### Multiply all numbers in the list

Input :  list1 = [1, 2, 3] 
Output : 6 
Explanation: 1*2*3=6 

Input : list1 = [3, 2, 4] 
Output : 24 

In [14]:
def mul(list1):
    result = 1
    for i in range(len(list1)):
        result = result * list1[i]
        i+=1
        
    return result
#driven code
lst = [12, 35, 9, 56, 24]


print(mul(lst))

5080320


In [15]:
#same problem with the input list 
def mult(list1):
    result = 1
    for i in range(len(list1)):
        result = result * list1[i]
        i+=1
        
    return result 





# driven code 
input_string = input("enter the list of integers seperated by space : ")
input_list = input_string.split()

my_list = []

for i in input_list:
    my_list.append(int(i))
    
print("the given list is : ", my_list)

print("the multiplication of numbers in the given list is : ", mult(my_list))

enter the list of integers seperated by space : 12
the given list is :  [12]
the multiplication of numbers in the given list is :  12


### Python program to find smallest number in a list


In [16]:
input_string = input("enter the list of integers seperated by sapce: ")
input_list = input_string.split()

list1 = []

for i in input_list:
    list1.append(int(i))

list1.sort()
print(list1)
print("smallest element is : ", list1[0])

enter the list of integers seperated by sapce: 2
[2]
smallest element is :  2


In [17]:
# using numpy

import numpy as np


lis = [5, 7, 2, 8, 9]

minimum = np.min(lis)


print("the smallest number in the list is", minimum)

the smallest number in the list is 2


### Python Program to Find Largest Number in a List


In [49]:
input_string = input("enter the list seperated by space : ")
input_list = input_string.split()

lis = []

for i in input_list:
    lis.append(int(i))
    
lis.sort(reverse = True) # it is the exact code for smallest no in the list except sort(reverse = True) 

print(lis)
print("the largest element in the list is : ", lis[0])

enter the list seperated by space : 1 2 6 4 8 
[8, 6, 4, 2, 1]
the largest element in the list is :  8


In [19]:
import numpy as np

lis = [5, 7, 2, 8, 9]


largest = np.max(lis)
print ("largest number in the list is :", largest)

largest number in the list is : 9


### Python program to find second largest number in a list

In [20]:
list1 = [10, 20, 4, 45, 99]
list1.sort() 
mx = list1[-2]
print("the second largest number in the list is ", mx)

the second largest number in the list is  45


In [21]:
list1 = [10, 20, 4, 45, 99]
list1.sort()
mx = max(list1[-1], list1[-2])
secondmax = min(list1[-1], list1[-2])
print("largest number in the list is :",mx)
print("second largest number in the list is :", secondmax)

largest number in the list is : 99
second largest number in the list is : 45


### find N largest elements from a list

In [33]:
list1 = [10, 20, 4, 45, 99]
n = int(input("rank wise number from the list when list is sorted decending "))
list1.sort(reverse = True)

print("sorted list is ", list1)
print("{} nd  largest element in the list is {} ".format(n,list1[n-1]))

rank wise number from the list when list is sorted decending 4
sorted list is  [99, 45, 20, 10, 4]
4 nd  largest element in the list is 10 


In [50]:
# with def function 
def n_th_largest_number(numbers, n):
    sorted_numbers = sorted(numbers,reverse = True)
    if n <= len(sorted_numbers):
        return sorted_numbers[n-1]
    else:
        return None
    
list1 = [10, 20, 4, 45, 99]
print("before sorting the element",list1)
n = int(input("enter the rank element after sorting :" ))

largest = n_th_largest_number(list1, n)

if largest is not None:
    
    print("{}th largest element in the list is {}".format(n, list1[n-1]))
else:
    print("valid rank tak na bhava, yaa list mde {} ch element ahet {} elements nahit.".format(len(list1),n))

before sorting the element [10, 20, 4, 45, 99]
enter the rank element after sorting :2
2th largest element in the list is 20


###  program to print even numbers in a list

In [45]:
list1 = [10, 20, 4, 45, 99]


for i in list1:
    if i % 2 == 0 :
        print(i, end =" ")
    
    


10 20 4 

In [48]:
def get_even_numbers(numbers):
    even_numbers = []
    
    for i in numbers:
        if i % 2 == 0:
            even_numbers.append(i)
    return even_numbers

#driven code

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_list = get_even_numbers(my_list)

print("even numbers in the given list are : ", even_list)

even numbers in the given list are :  [2, 4, 6, 8, 10]


In [59]:
# above code with input veraibles

def get_even_numbers(numbers):
    even_numbers = []
    
    for i in numbers:
        if i % 2 == 0:
            even_numbers.append(i)
    return even_numbers




#driven code
input_string = input("enter the list seperated by space :")
input_list = input_string.split()


list1 = []

for i in input_list:
    list1.append(int(i))
print(" the list before seperating between even and odd",list1)    
print(" even numbers in the list are ",get_even_numbers(list1))

enter the list seperated by space :4165 796 13 46 98
 the list before seperating between even and odd [4165, 796, 13, 46, 98]
 even numbers in the list are  [796, 46, 98]


### Python program to print odd numbers in a List


In [60]:
list1 = [10, 20, 4, 45, 99]


for i in list1:
    if i % 2 == 1:
        print ( i , end = " ")

45 99 

In [62]:
def odd_numbers(numbers):
    odd_numbers = []
    for i in numbers:
        if i % 2 == 1:
            odd_numbers.append(i)
            
    return odd_numbers

# driven code


list1 = [10, 20, 4, 45, 99]
print(" odd numbers in the list are : ",odd_numbers(list1))

 odd numbers in the list are :  [45, 99]


In [67]:
# same code with input parameters

def odd_numbers(numbers):
    odd_nums = []
    for i in numbers:
        if i % 2 == 1:
            odd_nums.append(i)
            
    return odd_nums


# driven code


string_input = input(" enter the numbers  in the list seeprated by space")
input_list = string_input.split()

list1 = []

for i in input_list:
    list1.append(int(i))
    
print("elements in the list before seperating are ", list1)
print("odd elements in the list are :", odd_numbers(list1))


 enter the numbers  in the list seeprated by space4654 977 13 46 79
elements in the list before seperating are  [4654, 977, 13, 46, 79]
odd elements in the list are : [977, 13, 79]


### to print all even numbers in a range

In [70]:
for even_number in range(22, 44, 2):
    print(even_number, end = " ")

22 24 26 28 30 32 34 36 38 40 42 

In [72]:
start = int(input("enter the starting point :"))
end  = int(input ("enter the ending point :"))

for even_number in range(start, end+ 1 , 2):
    print(even_number, end = " ")


enter the starting point :12
enter the ending point :69
12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 

In [78]:
start = int(input("enter the starting point :"))
end  = int(input ("enter the ending point :"))
print("even numbers in the range are:")
for i in range(start, end+ 1):
    if i % 2 == 0:
        print(i, end = " ")

    
    

enter the starting point :12
enter the ending point :69
even numbers in the range are:
12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 

### Python program to print all odd numbers in a range


In [82]:
print(" odd number in the range are :")
for odd_number in range(2, 45, 2):
    print(odd_number+1, end = " ")

 odd number in the range are :
3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 

In [83]:
start = int(input("enter the stating point in the range:"))
end = int(input("enter the ending point in the range:"))
print("odd numbers in the range are ")
for i in range(start, end+1 ,2):
    print(i+1, end = ",")

enter the stating point in the range:12
enter the ending point in the range:69

13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,

In [87]:
start = int(input("enter the stating point in the range:"))
end = int(input("enter the ending point in the range:"))
print("odd numbers in the range are : ")

for i in range(start, end+1):
    if i % 2 == 1:
        print(i, end = " ")

enter the stating point in the range:12
enter the ending point in the range:69
odd numbers in the range are : 
13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 

In [85]:
#using pass

start = int(input("enter the starting point : "))
end  = int(input("enter the ending point :"))

for i in range (start, end+1 ):
    if i % 2 == 0:
        pass
    else:
        print(i, end = " ")

enter the starting point : 12
enter the ending point :69
13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 

### Python program to print positive numbers in a list


In [94]:
string_input = input( "enter the list seperated by space :")
list_input = string_input.split()

list1 = []

for i in list_input:
    list1.append(int(i))
    
print("the list ",list1)
print("positive numbers in the list are :")  
for i in list1:
    if i >= 0:
        print(i, end = " ")
    
    

enter the list seperated by space :12 -75 -716 154 
the list  [12, -75, -716, 154]
positive numbers in the list are :
12 154 

In [97]:
# with list comprehensive
list1 = [-10, -21, -4, 45, -66, 93]


pos_nums = [i for i in list1 if i >= 0]

print("positive numbers in the list are : ", pos_nums)


positive numbers in the list are :  [45, 93]


### Python program to print negative numbers in a list


In [99]:
string_input = input (" enter the list seperated by spaces: ")
input_list = string_input.split()

list1 = []


for i in input_list:
    list1.append(int(i))

for i in list1:
    if i < 0:
        print(i, end = " ")

    

 enter the list seperated by spaces: -464 -465 -48 4451
-464 -465 -48 

### Python program to print all positive numbers in a range


In [13]:
for i in range(-12, 69):
    if i >= 0:
        print(i, end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 

In [14]:
start = int(input("enter the starting point in the range :"))
end = int(input("enter the end point of the range :"))
for i in range(start, end):
    if i >= 0:
        print(i, end = " ")

enter the starting point in the range :-12
enter the end point of the range :12
0 1 2 3 4 5 6 7 8 9 10 11 

In [16]:
# with pass statement 
for i in range(-12, 12):
    if i < 0:
        pass
    else:
        print(i, end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [29]:
# with lambda function 
list1 = []
for i in range(-12,12):
    list1.append(i)
    
print("numbers in the list are :", list1) 


positive_nums = list(filter(lambda x: (x >= 0), list1))

print("positive numbers in the list are : ", positive_nums)

numbers in the list are : [-12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
positive numbers in the list are :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


### Python program to print negative numbers in a Range


In [5]:
for i in range(-12,69):
    if i < 0:
        print(i , end = " ")

-12 -11 -10 -9 -8 -7 -6 -5 -4 -3 -2 -1 

In [9]:
start = int(input("enter the starting point in range: "))
end = int(input("enter the end point of the range: "))

for i in range(start, end):
    if i < 0:
        print(i, end = " ")

enter the starting point in range: -12
enter the end point of the range: 12
-12 -11 -10 -9 -8 -7 -6 -5 -4 -3 -2 -1 

In [24]:
# with lambda function 

list1 = []
for i in range(-12,69):
    list1.append(i)
    
print("numbers in the list are ",list1)  


negative_nums = list(filter(lambda x:(x<0), list1))
print("negative numbers in the list are : ",negative_nums)

numbers in the list are  [-12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]
negative numbers in the list are :  [-12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1]


### Remove multiple elements from a list in Python


In [32]:
list1 = [11, 5, 17, 18, 23, 50]


for i in list1:
    if i % 2 == 0:
        list1.remove(i)
        
print("the list after removal is :",list1)

the list after removal is : [11, 5, 17, 23]


In [35]:
list1 = []

for i in range(12,69):
    list1.append(i)
    
    
    
print("list before removing elements are : ", list1)
print("after removing the elements are : ")




for i in list1:
    if i %2 ==0:
        list1.remove(i)
        
        print(i, end = " ")

list before removing elements are  [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]
after removing the elements are : 
12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 

In [39]:
# with comprehansion 

list1 = [11, 5, 17, 18, 23, 50]
print("before applying any function ",list1)

list1 = [i for i in list1 if i % 2 != 0]

print(" after applying function ",list1)

before applying any function  [11, 5, 17, 18, 23, 50]
 after applying function  [11, 5, 17, 23]


In [ ]:
list1 = [11, 5, 17, 18, 23, 50]


list1 = [i ]

In [42]:
list1 = [11, 5, 17, 18, 23, 50]

list1 = [ elem for i,elem in enumerate(list1) if elem % 2 != 0]

print(list1)


[11, 5, 17, 23]


### Python – Remove empty List from List


In [50]:
test_list = [5, 6, [], 3, [], [], 9]
print(type(test_list))
# printing original list
print("The original list is : " + str(test_list))

test_list = [i for i in test_list if i != []]


print("list after the empty list removal : ", test_list)

<class 'list'>
The original list is : [5, 6, [], 3, [], [], 9]
list after the empty list removal :  [5, 6, 3, 9]


In [52]:
# with filter list 

test_list = [5, 6, [], 3, [], [], 9]


res = list(filter(lambda x: x !=[],test_list))

print("list after empty list removal",res)

list after empty list removal [5, 6, 3, 9]


In [65]:
test_list = [5, 6, [], 3, [], [], 9]
 
print("the original list is :" +  str(test_list))


res = list(map(lambda x: x if x != [] else None, test_list))

res = [x for x in res if x != None]

print("the list after removing the empty strings is :", res)

the original list is :[5, 6, [], 3, [], [], 9]
the list after removing the empty strings is : [5, 6, 3, 9]


In [63]:
# Initializing list
test_list = [5, 6, [], 3, [], [], 9]

# printing original list
print("The original list is : " + str(test_list))

# using map() function
res = list(map(lambda x: x if x != [] else None, test_list))
res = [x for x in res if x != None]

# printing result
print("List after empty list removal : " + str(res))


The original list is : [5, 6, [], 3, [], [], 9]
List after empty list removal : [5, 6, 3, 9]


### Cloning or Copying a list

In [70]:
import copy

test_list = [5, 6, [], 3, [], [], 9]


test= copy.copy(test_list)

print(test)

[5, 6, [], 3, [], [], 9]


### Count occurrences of an element in a list

Input: lst = [15, 6, 7, 10, 12, 20, 10, 28, 10], x = 10
Output: 3 
Explanation: 10 appears three times in given list.


In [71]:
def countx(lst, x):
    count = 0
    for i in lst:
        if (i == x):
            count += 1
    return count

lst = [11, 5, 17, 18, 23, 50, 5]


print(countx(lst,5 ))

2


In [80]:
def countx(lst, x):
    count = 0
    for i in lst:
        if (i == x):
            count += 1
    return count


string_input = input("enter the numbers seperated by space : ")
list_input = string_input.split()

lst = []

for i in list_input:
    lst.append(int(i))

print(countx(lst,1))

print 

enter the numbers seperated by space : 12 1 
1


### Remove empty tuples from a list

In [86]:
def remove_tuple(tuples):
    tuples = [ i for i in tuples if  i]
    return tuples

tuples = [(), ('ram','15','8'), (), ('laxman', 'sita'),
          ('krishna', 'akbar', '45'), ('',''),()]

print("after removing the empty tuples are :",remove_tuple(tuples))

after removing the empty tuples are : [('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ('', '')]


In [90]:
def remove(tuples):
    tuples = filter(None, tuples)
    return tuples

#driver code

tuples = [(), ('ram','15','8'), (), ('laxman', 'sita'),
          ('krishna', 'akbar', '45'), ('',''),()]

print(remove(tuples))




the above method will not work on python 3 it will work on python 2 

Using the inbuilt method filter() in Python, we can filter out the empty elements by passing the None as the parameter. This method works in both Python 2 and Python 3 and above, but the desired output is only shown in Python 2 because Python 3 returns a generator.

In [92]:
def remove(tuples):
    for i in tuples:
        if (i == ()):
            tuples.remove(i)
    return tuples

tuples = [(), ('ram','15','8'), (), ('laxman', 'sita'),
        ('krishna', 'akbar', '45'), ('',''),()]

print("list after removing empty list is :", remove(tuples))

list after removing empty list is : [('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ('', '')]


### Program to print duplicates from a list of integers

In [100]:
lis = [1, 2, 1, 2, 3, 4, 5, 1, 1, 2, 5, 6, 7, 8, 9, 9]

uniquelist = []
duplicatelist = []



for i in lis:
    if i not in uniquelist:
        uniquelist.append(i)
        if i not in duplicatelist:
            duplicatelist.append(i)
            
print(duplicatelist)
print(uniquelist)  

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


###  program to find Cumulative sum of a list

In [101]:
def cumsum(lists):
    cu_list = []
    length = len(lists)
    cu_list = [sum(lists[0:x:1]) for x in range(0,length+1)]
    return cu_list[1:]

lists = [10, 20, 30, 40, 50]
print(cumsum(lists))

[10, 30, 60, 100, 150]


In [105]:
list=[10,20,30,40,50]

new_list = []
cumsum = 0
print("the given list is : ", list)
for i in range(0, len(list)):
    cumsum = cumsum + list[i]
    new_list.append(cumsum)
    
print(" commulative sum of the list is :",new_list)

the given list is :  [10, 20, 30, 40, 50]
 commulative sum of the list is : [10, 30, 60, 100, 150]


### Sum of number digits in List

In [107]:
test_list = [12, 67, 98, 34]


print("the original list is :", test_list)


res = []
for ele in test_list:
    sum = 0
    for digit in str(ele):
        sum = sum +int(digit)
    res.append(sum)
    
    
print(" list integer summeation : ", str(res))

the original list is : [12, 67, 98, 34]
 list integer summeation :  [3, 13, 17, 7]


### Break a list into chunks of size N in Python


In [117]:
#Using yield



my_list = ['geeks', 'for', 'geeks', 'like',
           'geeky','nerdy', 'geek', 'love',
               'questions','words', 'life']
  
    
def divide_chunks(l, n):
    
    
    for i in range(0, len(l), n):
        yield l[i:n+1]

n=5


x = divide_chunks(my_list, n)

print(x)

<generator object divide_chunks at 0x00000285FB55E9D0>


In [123]:

my_list = [1, 2, 3, 4, 5,
           6, 7, 8, 9]
start = 0
end = len(my_list)
step = 4
for i in range(start, end, step):
    x= i
    print(my_list[x:x+step])
        

[1, 2, 3, 4]
[5, 6, 7, 8]
[9]


In [133]:
my_list = []

start = 12
end = 69
step = 4
for i in range(start, end):
    my_list.append(i)
    
print("the list before spliting is :", my_list)

for j in range(start, end , step):
        x = j
        print(my_list[x: x+step])

the list before spliting is : [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]
[24, 25, 26, 27]
[28, 29, 30, 31]
[32, 33, 34, 35]
[36, 37, 38, 39]
[40, 41, 42, 43]
[44, 45, 46, 47]
[48, 49, 50, 51]
[52, 53, 54, 55]
[56, 57, 58, 59]
[60, 61, 62, 63]
[64, 65, 66, 67]
[68]
[]
[]
[]


In [136]:
# using list comprehansive


my_list = [1, 2, 3, 4, 5,
              6, 7, 8, 9]

n = 4

final = [my_list[i * n :(i+1) * n] for i in range((len(my_list)+n -1)//n)]

print(final)

[[1, 2, 3, 4], [5, 6, 7, 8], [9]]


In [142]:
# using numpy
import numpy as np
arr = range(33)
np.array_split(arr, 11)

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14]),
 array([15, 16, 17]),
 array([18, 19, 20]),
 array([21, 22, 23]),
 array([24, 25, 26]),
 array([27, 28, 29]),
 array([30, 31, 32])]

### Sort the values of first list using second list in Python


Input : list1 = [“a”, “b”, “c”, “d”, “e”, “f”, “g”, “h”, “i”]
           list2 = [ 0,   1,   1,    0,   1,   2,   2,   0,   1]
Output : [‘a’, ‘d’, ‘h’, ‘b’, ‘c’, ‘e’, ‘i’, ‘f’, ‘g’]

Input : list1 = [“g”, “e”, “e”, “k”, “s”, “f”, “o”, “r”, “g”, “e”, “e”, “k”, “s”]
            list2 = [ 0,   1,   1,    0,   1,   2,   2,   0,   1]
Output : [‘g’, ‘k’, ‘r’, ‘e’, ‘e’, ‘g’, ‘s’, ‘f’, ‘o’]



In [149]:
def sort_list(list1, list2):
    zipped_pairs = zip(list2, list1)
    z = [ x for _, x in sorted(zipped_pairs)]
    
    
    return z



x = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]
y = [0,   1,   1,    0,   1,   2,   2,   0,   1]


print(sort_list(x, y))




['a', 'd', 'h', 'b', 'c', 'e', 'i', 'f', 'g']
['g', 'k', 'r', 'e', 'e', 'g', 's', 'f', 'o']


In [151]:
def sorted_list(list1, list2):
    idx = np.argsort(list2)
    return np.array(list1)[idx]


x = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]
y = [0, 1, 1, 0, 1, 2, 2, 0, 1]
 
print(sorted_list(x, y))

['a' 'd' 'h' 'b' 'c' 'e' 'i' 'f' 'g']
